### ISSUE TITLE
Fix small issues with branching

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/advanced-git-lesson#1]
Currently, if you try to create a new branch before pushing to remote, it returns an error:

`fatal: Not a valid object name: 'main'.`

I'm not sure whether this has something to do with the new name change or whether it's a different issue. If it comes up in the lesson it can be explained away but it's probably a good idea to fix for later.

Also, the worksheet for  "stage commit push" in my-new-branch is missing the push step.

**Comment by qdread** [comment]
Updated the missing push step but still don't know why the fatal comes up

**Comment by khondula** [comment]
I think this is now covered by #6 and #3

**Comment by qdread** [comment]
Yep I think that's right. I'll close this one ...
