### ISSUE TITLE
Link to general description of command line syntax

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/advanced-git-lesson#10]
This may be better to put in the git in the shell lesson. Some students hadn't seen unix style commands before so did not understand how they work... they are very cryptic after all. I don't know the best resource to link to for that.

**Comment by khondula** [comment]
not sure either. here are a few options? 

https://swcarpentry.github.io/shell-novice/reference/
https://www.cfa.harvard.edu/rtdc/shell_cmds/basic/
https://fs.r-lib.org/articles/function-comparisons.html (for comparison to r functions)

**Comment by qdread** [comment]
Thanks for the ideas!

**Comment by qdread** [comment]
Above carpentry link is broken but we can link to the whole lesson: https://swcarpentry.github.io/shell-novice/

**Comment by qdread** [comment]
Resolved in 0d638d0. Linked to carpentry lesson as well as explainshell.com which is kind of nifty
