### ISSUE TITLE
Make it clearer that you can use other command line tools

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/advanced-git-lesson#8]
This was left as a feedback by one of the students but I can't remember what it refers to (@reblake @khondula ???)

**Comment by qdread** [comment]
Basically, need to make sure the lesson can work outside of RStudio (TM) if some students don't want or need to use RStudio (TM). I think it more or less can, but for the classroom environment where the majority of people were using RStudio (TM), it was easier to just teach it that way. Still worth checking over the lesson to make sure there aren't places that require its use.

**Comment by khondula** [comment]
Where applicable, could also consider screenshots or references to how to accomplish the same things in jupyterlab via command line?

**Comment by qdread** [comment]
Honestly, now that I look at it more closely, this is probably more of a note for the instructor of the lesson. I looked over everything and it seems like the lesson adequately shows how to use the terminal and only shows RStudio as an alternative. I added some notes for instructors in the README.md for this repo which I think is probably good enough for now. Commit 7b7ebd6
